### PR TITLE
Unrestrict capybara test

### PR DESCRIPTION
**Pull request by luke-hill**

### CODE REVIEW

**Comment by luke-hill** [comment]
@twalpole I have finally managed to triage this weird behaviour down to a specific commit SHA - https://github.com/teamcapybara/capybara/commit/a76a35fbc8bb5baceb13c50ede1b9ee551f674d7

I'm not saying it's wrong, I'm just maybe asking you for help on this. It feels odd that the boolean check works, but the rspec matcher doesn't. I want to try help here so if I can provide anything else please ask.

@tgaff worked on this functionality, where we allow scoping inside of a block. **We also know it's a SitePrism interop issue**, not a Capybara issue. I was just wondering if you could help.

**Comment by twalpole** [comment]
This is happening because you're overwriting page and returning an element wrapper rather than a Capybara session. I think the element being used  should just implement the method `to_capybara_node` and return @root_element

**Comment by ineverov** [comment]
@luke-hill completely agree with @twalpole. Adding `to_capybara_node` to Section class solve the problem

**Comment by twalpole** [comment]
PR #65 - read description

**Pull request closed without merging**
