### PR TITLE
Fixing bug with Ruby 3 keyword arguments.

### PR DESCRIPTION
**Pull request by diego-aslz**
Without this fix, we get:

```
     Failure/Error: match { |actual| actual.public_send(object_method, *args) }

     ArgumentError:
       wrong number of arguments (given 2, expected 0..1)
     # ./vendor/bundle/ruby/3.0.0/gems/capybara-3.38.0/lib/capybara/node/matchers.rb:529:in `has_table?'
     # ./vendor/bundle/ruby/3.0.0/gems/capybara-3.38.0/lib/capybara/session.rb:773:in `has_table?'
     # ./lib/site_prism/rspec_matchers.rb:23:in `public_send'
     # ./lib/site_prism/rspec_matchers.rb:23:in `block (2 levels) in create_rspec_existence_matchers'
     # ./spec/site_prism/rspec_matchers_spec.rb:36:in `block (2 levels) in <top (required)>'
     # ./spec/site_prism/rspec_matchers_spec.rb:21:in `block (2 levels) in <top (required)>'
```

### CODE REVIEW

**Comment by luke-hill** [comment]
Can you try rebasing this with master and trying again. I think I made quite a simple error in the pipeline config.

**Comment by diego-aslz** [comment]
Sure!

**Comment by diego-aslz** [comment]
@luke-hill looks like that did the trick!

**Comment by luke-hill** [comment]
@diego-aslz https://github.com/site-prism/site_prism/commit/1a852a41872c845b69fe6b8ad9d3133837b177eb 🙈

**Review by luke-hill — CHANGES_REQUESTED** [review]
So we're using a few things here that I'm surprised haven't flagged from rubocop. But that's fine. We can tackle them regularly.

The class definition inside the test file seems odd and not needed. Instead we should be using a scoped `let`.

Once we've done this we should ensure we're calling this specific instances methods instead of using the `#page` alias. This is something we still "half" monkeypatch in SitePrism but will be removing soon

The core code I have no issues with.

Can you also look into writing a changelog entry in the same vein as others.

**Comment by luke-hill** [comment]
re-ping @diego-aslz can you let me know if you're able to look at this. I've been doing a bit more work in this repo in the last month starting to really tidy up the v4 beta prepping for a full v4 launch

**Comment by diego-aslz** [comment]
Sorry, this fell off my radar. I'll see if I can tackle it this weekend.

**Comment by diego-aslz** [comment]
@luke-hill pushed the adjustments. I moved the class into `fixtures`, seems like the right place?

**Review by luke-hill — COMMENTED** [review]
I've popped a comment on the problematic line. I'll try dedicate some time to fixing this this week

**Comment by luke-hill** [comment]
@diego-aslz I've had a go at fixing up the code you've done. But I'm confused around the spec you've used for Capybara matchers. Specifically I've never seen `rows` used as a matcher or `href`. Can you advise where you found this, maybe there's something missing in SitePrism. The error now looks legit. It complains about the keyword matcher being not understood.

**Comment by diego-aslz** [comment]
@luke-hill so sorry about the long delay here. So those filters in the spec are contrived and not really important, we can use whatever. We just need to use _some_ extra filter to trigger the Ruby 3 kwargs bug.

**Comment by luke-hill** [comment]
Rightio that's fine.

If you have time and can amend the filtering not to crash then go ahead. Failing that I'll get to this in the coming week

**Pull request merged**
